title: "Juan Melo – Cybersecurity"
email: "juanmt@uoc.edu"
description: >-
  Cybersecurity portfolio focused on Blue Team practices, traffic analysis, system hardening and cloud security.

url: "https://jmelo-sec.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

author:
  name: "Juan Melo"
  avatar: "/assets/img/profile.jpg"
  bio: "Computer Engineering · Cybersecurity · Blue Team · Cloud Security"
  github: jmelo-sec
  location: "Spain · Switzerland (future)"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true

include:
  - _pages

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
