title: "Juan Melo – Ciberseguridad"
email: "tuemail@example.com"
description: >-
  Portfolio profesional orientado a Blue Team, análisis de tráfico, hardening y seguridad cloud.

url: "https://jmelo-sec.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

author:
  name: "Juan Melo"
  avatar: "/assets/img/profile.jpg"
  bio: "Ingeniero Informático · Ciberseguridad · Blue Team · Cloud Security"
  github: jmelo-sec
  location: "España · Suiza (futuro)"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true

include:
  - _pages
